# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Hitheshkaranth.OpenTokenMonitor
PackageVersion: 0.4.1
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: OpenTokenMonitor
ReleaseDate: 2026-10-07
AppsAndFeaturesEntries:
- DisplayName: OpenTokenMonitor
  Publisher: opentokenmonitor
  ProductCode: OpenTokenMonitor
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\OpenTokenMonitor'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Hitheshkaranth/OpenTokenMonitor/releases/download/v0.4.1/OpenTokenMonitor_0.4.1_x64-setup.exe
  InstallerSha256: 4FAE6BA69AA5E83C68D4E44D571BD7D171BA4090576FF5D7EAC986C19CC7396A
ManifestType: installer
ManifestVersion: 1.12.0
